[package]
name = "rust-blockchain"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
data-encoding = "2.8.0"
num = "0.4.3"
serde = { version = "1.0", features = ["derive"] }
sha256 = "1.5.0"
